language: python
python:
  - 3.6
branches:
  only:
    - master
env:
  - DJANGO_VERSION=2.2.5
services:
  - postgresql
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - cp .env.example .env
  - python manage.py collectstatic --noinput
  - python manage.py migrate
script:
  - python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: "5fdd7bf5-e0f0-4e11-aa0d-bcaa455e5744"
  app: airlineapp-testing-ci-cd
  run:
    - python manage.py migrate
    - python manage.py runserver
  on: master
