language: python
python:
  - 3.6
branches:
  only:
    - master
env:
  - DJANGO_VERSION=2.2.5

services:
  - postgresql
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - cp .env.example .env
  - python manage.py migrate
script:
  - python mange.py test
