language: python
python:
  - 3.6
branches:
  only:
    - master
env:
  - DJANGO_VERSION=2.2.5
services:
  - postgresql
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE test;" -U postgres
  - cp .env.example .env
  - python manage.py migrate
script:
  - python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: airlineapp-testing-ci-cd
  run:
    - python manage.py migrate
    - echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')" | python manage.py shell
  on: master
